export default {
  estimate_id: null,
  item_id: null,
  line_uuid: null,
  line_photos: [],
  name: '',
  title: '',
  description: null,
  business_activity_type: 'service_bic',
  quantity: 1,
  price: 0,
  discount_type: 'fixed',
  discount_val: 0,
  discount: 0,
  total: 0,
  sub_total: 0,
  totalTax: 0,
  totalSimpleTax: 0,
  totalCompoundTax: 0,
  tax: 0,
  taxes: [],
}
